### ISSUE TITLE
Issue tracker is duplicated

### ISSUE THREAD

**Issue by kortschak** [kortschak/biogo#3]
This repository is secondary to code.google.com/p/biogo.

Please log issues at that tracker: http://code.google.com/p/biogo/issues/list

**Comment by abeconnelly** [comment]
Considering Google code is shutting down, is this the primary repository (and issue tracker) for biogo now?

**Comment by kortschak** [comment]
biogo is moving, yes. There was a post to biogo-users explaining the move (note that there is a year for this to happen - though the move is almost complete).

The new location is github.com/biogo.

I have not migrated all the repos (leaving some that are deprecated), a couple more may come across.
